title: Documentation 
description: Daily Documentation for my coursework and coding problems
theme: just-the-docs

url: https://Ali-Maq.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
